[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cron : actualisation automatique toutes les 30 minutes
[[plugins]]
  package = "@netlify/plugin-cron"
  [plugins.inputs]
    jobs = [
      { schedule = "*/30 * * * *", function = "stock-refresh-background" }
    ]
